install:
# necessary exports for build scripts
- if [ "$CXX" = "g++" ]; then export M2ETIS_COMPILER="gcc"; fi
- if [ "$CXX" = "clang++" ]; then export M2ETIS_COMPILER="clang"; fi
# change to correct gcc version
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.7" CC="gcc-4.7"; fi
- echo ${PATH}
- echo ${CXX}
- ${CXX} --version
- ${CXX} -v
addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise-3.7
        packages:
        - gcc-4.7
        - g++-4.7
os:
    - linux
language: cpp
compiler:
    - gcc
    - clang
script: ./travis.sh
env:
    matrix:
        - M2ETIS_TARGET=NoLoggingNoValgrindDebug M2ETIS_LOGGING=OFF M2ETIS_VALGRIND=OFF M2ETIS_BUILD_TYPE=Debug
        #- M2ETIS_TARGET=LoggingNoValgrindDebug M2ETIS_LOGGING=ON M2ETIS_VALGRIND=OFF M2ETIS_BUILD_TYPE=Debug
        - M2ETIS_TARGET=NoLoggingValgrindDebug M2ETIS_LOGGING=OFF M2ETIS_VALGRIND=ON M2ETIS_BUILD_TYPE=Debug
        #- M2ETIS_TARGET=LoggingValgrindDebug M2ETIS_LOGGING=ON M2ETIS_VALGRIND=ON M2ETIS_BUILD_TYPE=Debug
        - M2ETIS_TARGET=NoLoggingNoValgrindRelease M2ETIS_LOGGING=OFF M2ETIS_BUILD_TYPE=Release
        #- M2ETIS_TARGET=LoggingNoValgrindRelease M2ETIS_LOGGING=ON M2ETIS_BUILD_TYPE=Release

